version: "3"

services:
  app:
     build:
       context: . #our current directory, setting the context to
     ports:
       - "8000:8000"
     volumes:
       - ./app:/app
     command: >
       sh -c "python managed.py runserver 0.0.0.0:8000"


